<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>us.hebi.graalvm.samples</groupId>
        <artifactId>fx-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>native-executable</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>native-image-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>

                    <!-- compile native executable -->
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${graalvm.tools.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <mainClass>${mainClass}</mainClass>
                            <outputDirectory>${outputDir}</outputDirectory>
                            <imageName>${imageName}</imageName>
                            <sharedLibrary>false</sharedLibrary>
                            <useArgFile>false</useArgFile>
                            <skipNativeTests>true</skipNativeTests>
                            <verbose>true</verbose>
                        </configuration>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

</project>