<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>us.hebi.graalvm.samples</groupId>
        <artifactId>fx-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>native-sharedlib</artifactId>

    <dependencies>
        <dependency>
            <groupId>us.hebi.graalvm.samples</groupId>
            <artifactId>native-executable</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>

                    <!-- compile native shared library -->
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${graalvm.tools.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <mainClass>${mainClass}</mainClass>
                            <outputDirectory>${outputDir}</outputDirectory>
                            <imageName>${imageName}</imageName>
                            <sharedLibrary>true</sharedLibrary>
                            <useArgFile>false</useArgFile>
                            <skipNativeTests>true</skipNativeTests>
                            <verbose>true</verbose>
                        </configuration>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- create stubs and compile wrapper executables -->
                    <plugin>
                        <groupId>us.hebi.launchers</groupId>
                        <artifactId>native-launchers-maven-plugin</artifactId>
                        <version>1.0-SNAPSHOT</version>
                        <configuration>
                            <outputDirectory>${outputDir}</outputDirectory>
                            <imageName>${imageName}</imageName>
                            <compiler>${native.compiler}</compiler>
                            <launchers>
                                <launcher>
                                    <name>launcher-minimal</name>
                                    <mainClass>us.hebi.samples.gui.MinimalFxApp</mainClass>
                                    <console>true</console> <!-- show verbose debug info -->
                                </launcher>
                                <launcher>
                                    <name>launcher-verbose</name>
                                    <mainClass>us.hebi.samples.gui.MinimalFxAppLauncher</mainClass>
                                    <console>true</console> <!-- show verbose debug info -->
                                </launcher>
                            </launchers>
                        </configuration>
                        <executions>
                            <execution> <!-- before compilation and native-image -->
                                <id>generate-stubs</id>
                                <goals>
                                    <goal>gen-sources</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>build-executables</id>
                                <goals>
                                    <goal>build-launchers</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

</project>